"""empty message

Revision ID: 3d3791d4082f
Revises: f12407981b84
Create Date: 2018-06-26 15:19:38.784190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3791d4082f'
down_revision = 'f12407981b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('icon', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'icon')
    # ### end Alembic commands ###
